name: Build Android
on:
  push:
    branches: [master]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }
          expo-cache: true
      - name: install dependencies
        run: yarn install
      - name: build android
        run: expo build:android -t apk
      
