name: Build Android
on:
  push:
    branches: [master]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: expo
        uses: expo/expo-github-actions@v6
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: 4.x
      - name: install dependencies
        run: npm install
      - name: build android
        run: expo build:android -t apk



