name: Build Android
on:
  push:
    branches: [master]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          username: jainprashul
          password: ${{ secrets.EXPO_PASSWORD }}
      - name: install dependencies
        run: yarn install
      - name: publish update
        run: expo publish
      - name: export to github docs
        run: expo export --public-url https://jainprashul.github.io/An9where-App
      - name: build android
        run: expo build:android -t apk
